version: '3.8'

services:
  app:
    image: node:20
    container_name: adonis_app
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "${APP_PORT:-3333}:3333"
    command: sh -c "npm install && node ace serve --watch"
    depends_on:
      - db
    env_file: ".env"
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      NODE_ENV: development
      DB_CONNECTION: mysql
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB_NAME: ${DB_DATABASE}

  db:
    image: mysql:8.0
    container_name: adonis_mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    env_file: ".env"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  db_data:
